# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop
- fb/*

resources:
  containers:
  - container: my_container
    image: ubuntu:16.04
  - container: terraform
    image: hashicorp/terraform:1.3.8

pool:
  vmImage: ubuntu-latest

  container: hashicorp/terraform:1.3.8

stages:
  - stage: validate
    displayName: validate
    jobs:
    - job: validate
      # steps:
      # - task: TerraformCLI@0
        
      #   inputs:
      #     command: 'version'
      #     allowTelemetryCollection: true
      
      # - task: TerraformCLI@0
      #   inputs:
      #     command: 'validate'
      #     allowTelemetryCollection: true
        
      
      container: hashicorp/terraform:1.3.8
      steps:
        - bash: |
            terraform fmt -check=true -diff=true

    
  # - stage: build
  #   displayName: build
  #   jobs:
  #   - job: plan
  #     steps:
      
