# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop
- fb/*
pool:
  name: local

container: hashicorp/terraform:1.3.8

stages:
  - stage: validate
    displayName: validate
    jobs:
    - job: validate
      steps:
      - task: TerraformCLI@0
        inputs:
          command: 'version'
          allowTelemetryCollection: true
      
      - task: TerraformCLI@0
        inputs:
          command: 'validate'
          allowTelemetryCollection: true

    
  # - stage: build
  #   displayName: build
  #   jobs:
  #   - job: plan
  #     steps:
      
